name: web_dev_proxy
description: a web dev proxy server that has implement request cors and cookie cors, base on shelf_proxy
version: 1.0.0
repository: https://github.com/hss01248/flutter_web_dev_proxy
homepage: https://github.com/hss01248
email: hss012489@gmail.com
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.0
  path: ^1.8.0
  shelf: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
