name: web_dev_proxy
description: a web dev proxy server that has implement request cors and cookie cors, base on shelf_proxy
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  shelf_proxy: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
